service: nagraJsonToCsv 
package:
  #to include or exclude individually on the functions
  individually: true
  exclude:
    - '**/*'
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "s3:ListBucket"
          - "s3:PutObject"
        Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }  
functions:
  requesterFunc:
    handler: requester/wrap.handler
    package:
      include:
        - requester/**
    events:
      - http:
          path: playme
          method: get
  handlerFunc:
    handler: handler/wrap.handler
    package:
      include:
        - handler/**
    events:
      - s3:
          bucket: nagra-omdb
          event: s3:ObjectCreated:*
          rules:
            - prefix: jsonFolder
            - suffix: .json 

custom:
  pyIndividually:
    wrap:handlerFunc: handler/handler.jsonToCsv          # real handler
    wrap:requesterFunc: requester/requester.omdbrequest  # real handler
    dockerizedPip: True


plugins:
  #- serverless-python-requirements
  # https://www.npmjs.com/package/serverless-python-individually
  - serverless-python-individually


# resources:
#   Resources:
#     S3BucketOmdbBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: nagra-omdb
#         AccessControl: 'PublicReadWrite'
