service: nagraJsonToCsv 
package:
  #to include or exclude individually on the functions
  individually: true
  exclude:
    - '**/*'
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1
functions:
  requesterFunc:
    handler: requester/requester.omdbrequest
    package:
      include:
        - requester/**
    events:
      - http:
          path: playme
          method: get
  handlerFunc:
    handler: handler/handler.jsonToCsv
    package:
      include:
        - handler/**
    events:
      - s3:
          bucket: nagra-omdb
          event: s3:ObjectCreated:*
          rules:
            - prefix: jsonFolder
            - suffix: .json 

custom:
  pyIndividually:
    wrap:handlerFunc: handler/handler.jsonToCsv
    wrap:requesterFunc: requester/requester.omdbrequest
    dockerizedPip: True


plugins:
  #- serverless-python-requirements
  - serverless-python-individually


# resources:
#   Resources:
#     S3BucketOmdbBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: nagra-omdb
#         AccessControl: 'PublicReadWrite'
